name: Publish on Docker Hub

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        name: Set up QEMU
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
      - uses: docker/login-action@v2
        with:
          username: nim65s
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build main image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: nim65/cargo-binstall:latest
          platforms: linux/amd64,linux/arm64

      - name: Build mdbook image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: app.Dockerfile
          push: true
          build-args: APP=mdbook
          tags: nim65/cargo-binstall:mdbook
          platforms: linux/amd64,linux/arm64
